spring:
    profiles:
        active: dev
    application:
        name: Avaliacao de Desenvolvedor
    jpa:
        hibernate:
            ddl-auto: none
    liquibase:
        enabled: true
        change-log: classpath:liquibase/master.xml
server:
    port: 8080
jwt:
    secret: useSuaCriatividadeAquiEuNaoTenho
    # 1 mes
    expiration: 2629746000
